# Generated by Django 2.1.7 on 2019-02-16 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=1000)),
                ('length_ms', models.PositiveIntegerField()),
                ('uri', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('votes', models.IntegerField(default=0)),
                ('artists', models.ManyToManyField(blank=True, to='Voter.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.CharField(choices=[('1', 'Upvote'), ('0', 'Neutral'), ('-1', 'Downvote')], default='0', max_length=1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voter.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'song')},
        ),
    ]
