# Generated by Django 2.1.7 on 2019-02-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='upvote',
            field=models.CharField(choices=[('1', 'Upvote'), ('0', 'Neutral'), ('-1', 'Downvote')], default='0', max_length=2),
        ),
    ]
