# Generated by Django 2.1.7 on 2019-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
