# Generated by Django 2.1.7 on 2019-02-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0002_vote_upvote_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['votes']},
        ),
    ]
