# Generated by Django 2.1.7 on 2019-02-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0004_auto_20190214_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='song',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
